#include "RE/F/FormTypes.h"

namespace RE
{
	std::string_view FormTypeToString(RE::FormType a_formType) noexcept
	{
		switch (a_formType) {
		case RE::FormType::PluginInfo:
			return "TES4";
		case RE::FormType::FormGroup:
			return "GRUP";
		case RE::FormType::GameSetting:
			return "GMST";
		case RE::FormType::Keyword:
			return "KYWD";
		case RE::FormType::LocationRefType:
			return "LCRT";
		case RE::FormType::Action:
			return "AACT";
		case RE::FormType::TextureSet:
			return "TXST";
		case RE::FormType::MenuIcon:
			return "MICN";
		case RE::FormType::Global:
			return "GLOB";
		case RE::FormType::Class:
			return "CLAS";
		case RE::FormType::Faction:
			return "FACT";
		case RE::FormType::HeadPart:
			return "HDPT";
		case RE::FormType::Eyes:
			return "EYES";
		case RE::FormType::Race:
			return "RACE";
		case RE::FormType::Sound:
			return "SOUN";
		case RE::FormType::AcousticSpace:
			return "ASPC";
		case RE::FormType::Skill:
			return "SKIL";
		case RE::FormType::MagicEffect:
			return "MGEF";
		case RE::FormType::Script:
			return "SCPT";
		case RE::FormType::LandTexture:
			return "LTEX";
		case RE::FormType::Enchantment:
			return "ENCH";
		case RE::FormType::Spell:
			return "SPEL";
		case RE::FormType::Scroll:
			return "SCRL";
		case RE::FormType::Activator:
			return "ACTI";
		case RE::FormType::TalkingActivator:
			return "TACT";
		case RE::FormType::Armor:
			return "ARMO";
		case RE::FormType::Book:
			return "BOOK";
		case RE::FormType::Container:
			return "CONT";
		case RE::FormType::Door:
			return "DOOR";
		case RE::FormType::Ingredient:
			return "INGR";
		case RE::FormType::Light:
			return "LIGH";
		case RE::FormType::Misc:
			return "MISC";
		case RE::FormType::Apparatus:
			return "APPA";
		case RE::FormType::Static:
			return "STAT";
		case RE::FormType::StaticCollection:
			return "SCOL";
		case RE::FormType::MovableStatic:
			return "MSTT";
		case RE::FormType::Grass:
			return "GRAS";
		case RE::FormType::Tree:
			return "TREE";
		case RE::FormType::Flora:
			return "FLOR";
		case RE::FormType::Furniture:
			return "FURN";
		case RE::FormType::Weapon:
			return "WEAP";
		case RE::FormType::Ammo:
			return "AMMO";
		case RE::FormType::NPC:
			return "NPC_";
		case RE::FormType::LeveledNPC:
			return "LVLN";
		case RE::FormType::KeyMaster:
			return "KEYM";
		case RE::FormType::AlchemyItem:
			return "ALCH";
		case RE::FormType::IdleMarker:
			return "IDLM";
		case RE::FormType::Note:
			return "NOTE";
		case RE::FormType::ConstructibleObject:
			return "COBJ";
		case RE::FormType::Projectile:
			return "PROJ";
		case RE::FormType::Hazard:
			return "HAZD";
		case RE::FormType::SoulGem:
			return "SLGM";
		case RE::FormType::LeveledItem:
			return "LVLI";
		case RE::FormType::Weather:
			return "WTHR";
		case RE::FormType::Climate:
			return "CLMT";
		case RE::FormType::ShaderParticleGeometryData:
			return "SPGD";
		case RE::FormType::ReferenceEffect:
			return "RFCT";
		case RE::FormType::Region:
			return "REGN";
		case RE::FormType::Navigation:
			return "NAVI";
		case RE::FormType::Cell:
			return "CELL";
		case RE::FormType::Reference:
			return "REFR";
		case RE::FormType::ActorCharacter:
			return "ACHR";
		case RE::FormType::ProjectileMissile:
			return "PMIS";
		case RE::FormType::ProjectileArrow:
			return "PARW";
		case RE::FormType::ProjectileGrenade:
			return "PGRE";
		case RE::FormType::ProjectileBeam:
			return "PBEA";
		case RE::FormType::ProjectileFlame:
			return "PFLA";
		case RE::FormType::ProjectileCone:
			return "PCON";
		case RE::FormType::ProjectileBarrier:
			return "PBAR";
		case RE::FormType::PlacedHazard:
			return "PHZD";
		case RE::FormType::WorldSpace:
			return "WRLD";
		case RE::FormType::Land:
			return "LAND";
		case RE::FormType::NavMesh:
			return "NAVM";
		case RE::FormType::TLOD:
			return "TLOD";
		case RE::FormType::Dialogue:
			return "DIAL";
		case RE::FormType::Info:
			return "INFO";
		case RE::FormType::Quest:
			return "QUST";
		case RE::FormType::Idle:
			return "IDLE";
		case RE::FormType::Package:
			return "PACK";
		case RE::FormType::CombatStyle:
			return "CSTY";
		case RE::FormType::LoadScreen:
			return "LSCR";
		case RE::FormType::LeveledSpell:
			return "LVSP";
		case RE::FormType::AnimatedObject:
			return "ANIO";
		case RE::FormType::Water:
			return "WATR";
		case RE::FormType::EffectShader:
			return "EFSH";
		case RE::FormType::TOFT:
			return "TOFT";
		case RE::FormType::Explosion:
			return "EXPL";
		case RE::FormType::Debris:
			return "DEBR";
		case RE::FormType::ImageSpace:
			return "IMGS";
		case RE::FormType::ImageAdapter:
			return "IMAD";
		case RE::FormType::FormList:
			return "FLST";
		case RE::FormType::Perk:
			return "PERK";
		case RE::FormType::BodyPartData:
			return "BPTD";
		case RE::FormType::AddonNode:
			return "ADDN";
		case RE::FormType::ActorValueInfo:
			return "AVIF";
		case RE::FormType::CameraShot:
			return "CAMS";
		case RE::FormType::CameraPath:
			return "CPTH";
		case RE::FormType::VoiceType:
			return "VTYP";
		case RE::FormType::MaterialType:
			return "MATT";
		case RE::FormType::Impact:
			return "IPCT";
		case RE::FormType::ImpactDataSet:
			return "IPDS";
		case RE::FormType::Armature:
			return "ARMA";
		case RE::FormType::EncounterZone:
			return "ECZN";
		case RE::FormType::Location:
			return "LCTN";
		case RE::FormType::Message:
			return "MESG";
		case RE::FormType::Ragdoll:
			return "RGDL";
		case RE::FormType::DefaultObject:
			return "DOBJ";
		case RE::FormType::LightingMaster:
			return "LGTM";
		case RE::FormType::MusicType:
			return "MUSC";
		case RE::FormType::Footstep:
			return "FSTP";
		case RE::FormType::FootstepSet:
			return "FSTS";
		case RE::FormType::StoryManagerBranchNode:
			return "SMBN";
		case RE::FormType::StoryManagerQuestNode:
			return "SMQN";
		case RE::FormType::StoryManagerEventNode:
			return "SMEN";
		case RE::FormType::DialogueBranch:
			return "DLBR";
		case RE::FormType::MusicTrack:
			return "MUST";
		case RE::FormType::DialogueView:
			return "DLVW";
		case RE::FormType::WordOfPower:
			return "WOOP";
		case RE::FormType::Shout:
			return "SHOU";
		case RE::FormType::EquipSlot:
			return "EQUP";
		case RE::FormType::Relationship:
			return "RELA";
		case RE::FormType::Scene:
			return "SCEN";
		case RE::FormType::AssociationType:
			return "ASTP";
		case RE::FormType::Outfit:
			return "OTFT";
		case RE::FormType::ArtObject:
			return "ARTO";
		case RE::FormType::MaterialObject:
			return "MATO";
		case RE::FormType::MovementType:
			return "MOVT";
		case RE::FormType::SoundRecord:
			return "SNDR";
		case RE::FormType::DualCastData:
			return "DUAL";
		case RE::FormType::SoundCategory:
			return "SNCT";
		case RE::FormType::SoundOutputModel:
			return "SOPM";
		case RE::FormType::CollisionLayer:
			return "COLL";
		case RE::FormType::ColorForm:
			return "CLFM";
		case RE::FormType::ReverbParam:
			return "REVB";
		case RE::FormType::LensFlare:
			return "LENS";
		case RE::FormType::LensSprite:
			return "LSPR";
		case RE::FormType::VolumetricLighting:
			return "VOLI";
		default:
			return "NONE";
		}
	}
}
