#pragma once

#include "REL/Relocation.h"

namespace RE
{
#ifdef SKYRIM_SUPPORT_AE
	inline constexpr REL::ID NiRTTI_BGSAddonNodeSoundHandleExtra{ 400793 };
	inline constexpr REL::ID NiRTTI_BGSDecalNode{ 400564 };
	inline constexpr REL::ID NiRTTI_BSAnimGroupSequence{ 400606 };
	inline constexpr REL::ID NiRTTI_BSAnimInteractionMarker{ 411294 };
	inline constexpr REL::ID NiRTTI_BSAnimNote{ 410999 };
	inline constexpr REL::ID NiRTTI_BSAnimNotes{ 411000 };
	inline constexpr REL::ID NiRTTI_BSBehaviorGraphExtraData{ 411261 };
	inline constexpr REL::ID NiRTTI_BSBlastNode{ 411238 };
	inline constexpr REL::ID NiRTTI_BSBlendTreadTransfInterpolator{ 410939 };
	inline constexpr REL::ID NiRTTI_BSBloodSplatterShaderProperty{ 414853 };
	inline constexpr REL::ID NiRTTI_BSBodyMorphOffsetsExtraData{ 411260 };
	inline constexpr REL::ID NiRTTI_BSBoneLODExtraData{ 411326 };
	inline constexpr REL::ID NiRTTI_BSBoneMap{ 411292 };
	inline constexpr REL::ID NiRTTI_BSBound{ 411288 };
	inline constexpr REL::ID NiRTTI_BSClearZNode{ 415282 };
	inline constexpr REL::ID NiRTTI_BSCubeMapCamera{ 415229 };
	inline constexpr REL::ID NiRTTI_BSCullingProcess{ 411266 };
	inline constexpr REL::ID NiRTTI_BSDamageStage{ 411240 };
	inline constexpr REL::ID NiRTTI_BSDebrisNode{ 411239 };
	inline constexpr REL::ID NiRTTI_BSDecalPlacementVectorExtraData{ 411330 };
	inline constexpr REL::ID NiRTTI_BSDismemberSkinInstance{ 410521 };
	inline constexpr REL::ID NiRTTI_BSDistantObjectLargeRefExtraData{ 411304 };
	inline constexpr REL::ID NiRTTI_BSDistantTreeShaderProperty{ 415170 };
	inline constexpr REL::ID NiRTTI_BSDoorHavokController{ 404129 };
	inline constexpr REL::ID NiRTTI_BSDynamicLines{ 415308 };
	inline constexpr REL::ID NiRTTI_BSDynamicTriShape{ 410533 };
	inline constexpr REL::ID NiRTTI_BSEffectShaderProperty{ 414781 };
	inline constexpr REL::ID NiRTTI_BSEffectShaderPropertyColorController{ 415359 };
	inline constexpr REL::ID NiRTTI_BSEffectShaderPropertyFloatController{ 415357 };
	inline constexpr REL::ID NiRTTI_BSFaceGenAnimationData{ 401677 };
	inline constexpr REL::ID NiRTTI_BSFaceGenBaseMorphExtraData{ 401737 };
	inline constexpr REL::ID NiRTTI_BSFaceGenModelExtraData{ 401733 };
	inline constexpr REL::ID NiRTTI_BSFaceGenMorphData{ 401738 };
	inline constexpr REL::ID NiRTTI_BSFaceGenMorphDataHair{ 401740 };
	inline constexpr REL::ID NiRTTI_BSFaceGenMorphDataHead{ 401739 };
	inline constexpr REL::ID NiRTTI_BSFaceGenNiNode{ 401747 };
	inline constexpr REL::ID NiRTTI_BSFadeNode{ 414559 };
	inline constexpr REL::ID NiRTTI_BSFadeNodeCuller{ 415164 };
	inline constexpr REL::ID NiRTTI_BSFlattenedBoneTree{ 410520 };
	inline constexpr REL::ID NiRTTI_BSFogProperty{ 415262 };
	inline constexpr REL::ID NiRTTI_BSFrustumFOVController{ 411005 };
	inline constexpr REL::ID NiRTTI_BSFurnitureMarkerNode{ 411273 };
	inline constexpr REL::ID NiRTTI_BSGeometry{ 410531 };
	inline constexpr REL::ID NiRTTI_BSGeometryListCullingProcess{ 411301 };
	inline constexpr REL::ID NiRTTI_BSGrabIKNote{ 411001 };
	inline constexpr REL::ID NiRTTI_BSGrassShaderProperty{ 414683 };
	inline constexpr REL::ID NiRTTI_BSInstanceTriShape{ 411342 };
	inline constexpr REL::ID NiRTTI_BSInvMarker{ 411324 };
	inline constexpr REL::ID NiRTTI_BSLODMultiIndexTriShape{ 415482 };
	inline constexpr REL::ID NiRTTI_BSLODTriShape{ 410597 };
	inline constexpr REL::ID NiRTTI_BSLagBoneController{ 411338 };
	inline constexpr REL::ID NiRTTI_BSLeafAnimNode{ 414564 };
	inline constexpr REL::ID NiRTTI_BSLightingShaderProperty{ 414675 };
	inline constexpr REL::ID NiRTTI_BSLightingShaderPropertyColorController{ 415346 };
	inline constexpr REL::ID NiRTTI_BSLightingShaderPropertyFloatController{ 415340 };
	inline constexpr REL::ID NiRTTI_BSLightingShaderPropertyUShortController{ 415343 };
	inline constexpr REL::ID NiRTTI_BSLines{ 415307 };
	inline constexpr REL::ID NiRTTI_BSLookIKNote{ 411002 };
	inline constexpr REL::ID NiRTTI_BSMasterParticleSystem{ 411318 };
	inline constexpr REL::ID NiRTTI_BSMeshLODTriShape{ 415481 };
	inline constexpr REL::ID NiRTTI_BSMultiBound{ 411149 };
	inline constexpr REL::ID NiRTTI_BSMultiBoundAABB{ 411152 };
	inline constexpr REL::ID NiRTTI_BSMultiBoundCapsule{ 411334 };
	inline constexpr REL::ID NiRTTI_BSMultiBoundNode{ 411291 };
	inline constexpr REL::ID NiRTTI_BSMultiBoundOBB{ 411154 };
	inline constexpr REL::ID NiRTTI_BSMultiBoundRoom{ 411150 };
	inline constexpr REL::ID NiRTTI_BSMultiBoundShape{ 411251 };
	inline constexpr REL::ID NiRTTI_BSMultiBoundSphere{ 411252 };
	inline constexpr REL::ID NiRTTI_BSMultiIndexTriShape{ 415310 };
	inline constexpr REL::ID NiRTTI_BSMultiStreamInstanceTriShape{ 411246 };
	inline constexpr REL::ID NiRTTI_BSMultiTargetTreadTransfController{ 410643 };
	inline constexpr REL::ID NiRTTI_BSNiAlphaPropertyTestRefController{ 415360 };
	inline constexpr REL::ID NiRTTI_BSNiNode{ 411341 };
	inline constexpr REL::ID NiRTTI_BSNodeReferences{ 411329 };
	inline constexpr REL::ID NiRTTI_BSNonUniformScaleExtraData{ 411339 };
	inline constexpr REL::ID NiRTTI_BSOcclusionBox{ 411254 };
	inline constexpr REL::ID NiRTTI_BSOcclusionPlane{ 411256 };
	inline constexpr REL::ID NiRTTI_BSOcclusionShape{ 411194 };
	inline constexpr REL::ID NiRTTI_BSOrderedNode{ 415306 };
	inline constexpr REL::ID NiRTTI_BSPSysArrayEmitter{ 411241 };
	inline constexpr REL::ID NiRTTI_BSPSysHavokUpdateModifier{ 411049 };
	inline constexpr REL::ID NiRTTI_BSPSysInheritVelocityModifier{ 411113 };
	inline constexpr REL::ID NiRTTI_BSPSysLODModifier{ 415362 };
	inline constexpr REL::ID NiRTTI_BSPSysMultiTargetEmitterCtlr{ 411299 };
	inline constexpr REL::ID NiRTTI_BSPSysRecycleBoundModifier{ 411112 };
	inline constexpr REL::ID NiRTTI_BSPSysScaleModifier{ 411337 };
	inline constexpr REL::ID NiRTTI_BSPSysSimpleColorModifier{ 415361 };
	inline constexpr REL::ID NiRTTI_BSPSysStripUpdateModifier{ 411335 };
	inline constexpr REL::ID NiRTTI_BSPSysSubTexModifier{ 411336 };
	inline constexpr REL::ID NiRTTI_BSParabolicCullingProcess{ 415480 };
	inline constexpr REL::ID NiRTTI_BSParentVelocityModifier{ 411331 };
	inline constexpr REL::ID NiRTTI_BSParticleShaderProperty{ 414937 };
	inline constexpr REL::ID NiRTTI_BSParticleSystemManager{ 411269 };
	inline constexpr REL::ID NiRTTI_BSPlayerDistanceCheckController{ 404130 };
	inline constexpr REL::ID NiRTTI_BSPortal{ 411257 };
	inline constexpr REL::ID NiRTTI_BSPortalSharedNode{ 411258 };
	inline constexpr REL::ID NiRTTI_BSProceduralLightningController{ 411323 };
	inline constexpr REL::ID NiRTTI_BSRangeNode{ 411234 };
	inline constexpr REL::ID NiRTTI_BSReference{ 411328 };
	inline constexpr REL::ID NiRTTI_BSRotAccumTransfInterpolator{ 411003 };
	inline constexpr REL::ID NiRTTI_BSSceneGraph{ 411296 };
	inline constexpr REL::ID NiRTTI_BSSegmentedTriShape{ 410599 };
	inline constexpr REL::ID NiRTTI_BSShaderAccumulator{ 414751 };
	inline constexpr REL::ID NiRTTI_BSShaderProperty{ 414563 };
	inline constexpr REL::ID NiRTTI_BSShaderTextureSet{ 415049 };
	inline constexpr REL::ID NiRTTI_BSSimpleScaleController{ 404131 };
	inline constexpr REL::ID NiRTTI_BSSkyShaderProperty{ 415149 };
	inline constexpr REL::ID NiRTTI_BSSplatterExtraData{ 400667 };
	inline constexpr REL::ID NiRTTI_BSStripPSysData{ 411110 };
	inline constexpr REL::ID NiRTTI_BSStripParticleSystem{ 411055 };
	inline constexpr REL::ID NiRTTI_BSSubIndexLandTriShape{ 415484 };
	inline constexpr REL::ID NiRTTI_BSSubIndexTriShape{ 411303 };
	inline constexpr REL::ID NiRTTI_BSTempEffect{ 402009 };
	inline constexpr REL::ID NiRTTI_BSTempEffectDebris{ 402018 };
	inline constexpr REL::ID NiRTTI_BSTempEffectGeometryDecal{ 402021 };
	inline constexpr REL::ID NiRTTI_BSTempEffectParticle{ 402032 };
	inline constexpr REL::ID NiRTTI_BSTempEffectSPG{ 402037 };
	inline constexpr REL::ID NiRTTI_BSTempEffectSimpleDecal{ 402035 };
	inline constexpr REL::ID NiRTTI_BSTempNode{ 411190 };
	inline constexpr REL::ID NiRTTI_BSTempNodeManager{ 411189 };
	inline constexpr REL::ID NiRTTI_BSTextureSet{ 415048 };
	inline constexpr REL::ID NiRTTI_BSTreadTransfInterpolator{ 411004 };
	inline constexpr REL::ID NiRTTI_BSTreeNode{ 414565 };
	inline constexpr REL::ID NiRTTI_BSTriShape{ 410508 };
	inline constexpr REL::ID NiRTTI_BSValueNode{ 411158 };
	inline constexpr REL::ID NiRTTI_BSWArray{ 411332 };
	inline constexpr REL::ID NiRTTI_BSWaterShaderProperty{ 414852 };
	inline constexpr REL::ID NiRTTI_BSWindModifier{ 411185 };
	inline constexpr REL::ID NiRTTI_BSXFlags{ 411156 };
	inline constexpr REL::ID NiRTTI_DebugTextExtraData{ 412094 };
	inline constexpr REL::ID NiRTTI_ModelReferenceEffect{ 402943 };
	inline constexpr REL::ID NiRTTI_NiAVObject{ 410476 };
	inline constexpr REL::ID NiRTTI_NiAVObjectPalette{ 410557 };
	inline constexpr REL::ID NiRTTI_NiAccumulator{ 410605 };
	inline constexpr REL::ID NiRTTI_NiAdditionalGeometryData{ 410598 };
	inline constexpr REL::ID NiRTTI_NiAlphaAccumulator{ 410569 };
	inline constexpr REL::ID NiRTTI_NiAlphaProperty{ 410511 };
	inline constexpr REL::ID NiRTTI_NiAmbientLight{ 410570 };
	inline constexpr REL::ID NiRTTI_NiBSBoneLODController{ 411263 };
	inline constexpr REL::ID NiRTTI_NiBSPNode{ 410573 };
	inline constexpr REL::ID NiRTTI_NiBSplineBasisData{ 410967 };
	inline constexpr REL::ID NiRTTI_NiBSplineColorInterpolator{ 410969 };
	inline constexpr REL::ID NiRTTI_NiBSplineCompColorInterpolator{ 410970 };
	inline constexpr REL::ID NiRTTI_NiBSplineCompFloatInterpolator{ 410971 };
	inline constexpr REL::ID NiRTTI_NiBSplineCompPoint3Interpolator{ 410972 };
	inline constexpr REL::ID NiRTTI_NiBSplineCompTransformInterpolator{ 410973 };
	inline constexpr REL::ID NiRTTI_NiBSplineData{ 410968 };
	inline constexpr REL::ID NiRTTI_NiBSplineFloatInterpolator{ 410974 };
	inline constexpr REL::ID NiRTTI_NiBSplineInterpolator{ 411040 };
	inline constexpr REL::ID NiRTTI_NiBSplinePoint3Interpolator{ 410975 };
	inline constexpr REL::ID NiRTTI_NiBSplineTransformInterpolator{ 410976 };
	inline constexpr REL::ID NiRTTI_NiBackToFrontAccumulator{ 410604 };
	inline constexpr REL::ID NiRTTI_NiBillboardNode{ 410539 };
	inline constexpr REL::ID NiRTTI_NiBinaryExtraData{ 410571 };
	inline constexpr REL::ID NiRTTI_NiBlendAccumTransformInterpolator{ 410933 };
	inline constexpr REL::ID NiRTTI_NiBlendBoolInterpolator{ 410960 };
	inline constexpr REL::ID NiRTTI_NiBlendColorInterpolator{ 410961 };
	inline constexpr REL::ID NiRTTI_NiBlendFloatInterpolator{ 410930 };
	inline constexpr REL::ID NiRTTI_NiBlendInterpolator{ 410641 };
	inline constexpr REL::ID NiRTTI_NiBlendPoint3Interpolator{ 410962 };
	inline constexpr REL::ID NiRTTI_NiBlendQuaternionInterpolator{ 410963 };
	inline constexpr REL::ID NiRTTI_NiBlendTransformInterpolator{ 410929 };
	inline constexpr REL::ID NiRTTI_NiBoolData{ 410964 };
	inline constexpr REL::ID NiRTTI_NiBoolInterpController{ 411044 };
	inline constexpr REL::ID NiRTTI_NiBoolInterpolator{ 410965 };
	inline constexpr REL::ID NiRTTI_NiBoolTimelineInterpolator{ 410966 };
	inline constexpr REL::ID NiRTTI_NiBooleanExtraData{ 410572 };
	inline constexpr REL::ID NiRTTI_NiCamera{ 410506 };
	inline constexpr REL::ID NiRTTI_NiCollisionData{ 410614 };
	inline constexpr REL::ID NiRTTI_NiCollisionObject{ 415305 };
	inline constexpr REL::ID NiRTTI_NiColorData{ 410921 };
	inline constexpr REL::ID NiRTTI_NiColorExtraData{ 410574 };
	inline constexpr REL::ID NiRTTI_NiColorExtraDataController{ 410977 };
	inline constexpr REL::ID NiRTTI_NiColorInterpolator{ 410922 };
	inline constexpr REL::ID NiRTTI_NiControllerManager{ 410635 };
	inline constexpr REL::ID NiRTTI_NiControllerSequence{ 410638 };
	inline constexpr REL::ID NiRTTI_NiCullingProcess{ 410541 };
	inline constexpr REL::ID NiRTTI_NiDefaultAVObjectPalette{ 410535 };
	inline constexpr REL::ID NiRTTI_NiDirectionalLight{ 410540 };
	inline constexpr REL::ID NiRTTI_NiExtraData{ 410528 };
	inline constexpr REL::ID NiRTTI_NiExtraDataController{ 411039 };
	inline constexpr REL::ID NiRTTI_NiFloatController{ 411043 };
	inline constexpr REL::ID NiRTTI_NiFloatData{ 410919 };
	inline constexpr REL::ID NiRTTI_NiFloatExtraData{ 410575 };
	inline constexpr REL::ID NiRTTI_NiFloatExtraDataController{ 410931 };
	inline constexpr REL::ID NiRTTI_NiFloatInterpController{ 411042 };
	inline constexpr REL::ID NiRTTI_NiFloatInterpolator{ 410920 };
	inline constexpr REL::ID NiRTTI_NiFloatsExtraData{ 410576 };
	inline constexpr REL::ID NiRTTI_NiFloatsExtraDataController{ 410978 };
	inline constexpr REL::ID NiRTTI_NiFloatsExtraDataPoint3Controller{ 410979 };
	inline constexpr REL::ID NiRTTI_NiFogProperty{ 410577 };
	inline constexpr REL::ID NiRTTI_NiGeometry{ 410558 };
	inline constexpr REL::ID NiRTTI_NiGeometryData{ 410529 };
	inline constexpr REL::ID NiRTTI_NiIntegerExtraData{ 410579 };
	inline constexpr REL::ID NiRTTI_NiIntegersExtraData{ 410580 };
	inline constexpr REL::ID NiRTTI_NiInterpController{ 410644 };
	inline constexpr REL::ID NiRTTI_NiInterpolator{ 410934 };
	inline constexpr REL::ID NiRTTI_NiKeyBasedInterpolator{ 410942 };
	inline constexpr REL::ID NiRTTI_NiKeyframeManager{ 410980 };
	inline constexpr REL::ID NiRTTI_NiLight{ 410503 };
	inline constexpr REL::ID NiRTTI_NiLightColorController{ 410981 };
	inline constexpr REL::ID NiRTTI_NiLightDimmerController{ 410982 };
	inline constexpr REL::ID NiRTTI_NiLookAtController{ 410983 };
	inline constexpr REL::ID NiRTTI_NiLookAtInterpolator{ 410984 };
	inline constexpr REL::ID NiRTTI_NiMeshPSysData{ 411062 };
	inline constexpr REL::ID NiRTTI_NiMeshParticleSystem{ 411051 };
	inline constexpr REL::ID NiRTTI_NiMorphData{ 410985 };
	inline constexpr REL::ID NiRTTI_NiMultiTargetTransformController{ 410642 };
	inline constexpr REL::ID NiRTTI_NiNode{ 410481 };
	inline constexpr REL::ID NiRTTI_NiObject{ 410472 };
	inline constexpr REL::ID NiRTTI_NiObjectNET{ 410491 };
	inline constexpr REL::ID NiRTTI_NiPSysAgeDeathModifier{ 411067 };
	inline constexpr REL::ID NiRTTI_NiPSysAirFieldAirFrictionCtlr{ 411063 };
	inline constexpr REL::ID NiRTTI_NiPSysAirFieldInheritVelocityCtlr{ 411064 };
	inline constexpr REL::ID NiRTTI_NiPSysAirFieldModifier{ 411065 };
	inline constexpr REL::ID NiRTTI_NiPSysAirFieldSpreadCtlr{ 411066 };
	inline constexpr REL::ID NiRTTI_NiPSysBombModifier{ 411068 };
	inline constexpr REL::ID NiRTTI_NiPSysBoundUpdateModifier{ 411069 };
	inline constexpr REL::ID NiRTTI_NiPSysBoxEmitter{ 411070 };
	inline constexpr REL::ID NiRTTI_NiPSysCollider{ 411118 };
	inline constexpr REL::ID NiRTTI_NiPSysColliderManager{ 411071 };
	inline constexpr REL::ID NiRTTI_NiPSysColorModifier{ 411072 };
	inline constexpr REL::ID NiRTTI_NiPSysCylinderEmitter{ 411054 };
	inline constexpr REL::ID NiRTTI_NiPSysData{ 411073 };
	inline constexpr REL::ID NiRTTI_NiPSysDragFieldModifier{ 411074 };
	inline constexpr REL::ID NiRTTI_NiPSysDragModifier{ 411075 };
	inline constexpr REL::ID NiRTTI_NiPSysEmitter{ 411056 };
	inline constexpr REL::ID NiRTTI_NiPSysEmitterCtlr{ 411047 };
	inline constexpr REL::ID NiRTTI_NiPSysEmitterCtlrData{ 411076 };
	inline constexpr REL::ID NiRTTI_NiPSysEmitterDeclinationCtlr{ 411077 };
	inline constexpr REL::ID NiRTTI_NiPSysEmitterDeclinationVarCtlr{ 411078 };
	inline constexpr REL::ID NiRTTI_NiPSysEmitterInitialRadiusCtlr{ 411079 };
	inline constexpr REL::ID NiRTTI_NiPSysEmitterLifeSpanCtlr{ 411080 };
	inline constexpr REL::ID NiRTTI_NiPSysEmitterPlanarAngleCtlr{ 411081 };
	inline constexpr REL::ID NiRTTI_NiPSysEmitterPlanarAngleVarCtlr{ 411082 };
	inline constexpr REL::ID NiRTTI_NiPSysEmitterSpeedCtlr{ 411083 };
	inline constexpr REL::ID NiRTTI_NiPSysFieldAttenuationCtlr{ 411084 };
	inline constexpr REL::ID NiRTTI_NiPSysFieldMagnitudeCtlr{ 411085 };
	inline constexpr REL::ID NiRTTI_NiPSysFieldMaxDistanceCtlr{ 411086 };
	inline constexpr REL::ID NiRTTI_NiPSysFieldModifier{ 411116 };
	inline constexpr REL::ID NiRTTI_NiPSysGravityFieldModifier{ 411087 };
	inline constexpr REL::ID NiRTTI_NiPSysGravityModifier{ 411048 };
	inline constexpr REL::ID NiRTTI_NiPSysGravityStrengthCtlr{ 411088 };
	inline constexpr REL::ID NiRTTI_NiPSysGrowFadeModifier{ 411089 };
	inline constexpr REL::ID NiRTTI_NiPSysInitialRotAngleCtlr{ 411090 };
	inline constexpr REL::ID NiRTTI_NiPSysInitialRotAngleVarCtlr{ 411091 };
	inline constexpr REL::ID NiRTTI_NiPSysInitialRotSpeedCtlr{ 411092 };
	inline constexpr REL::ID NiRTTI_NiPSysInitialRotSpeedVarCtlr{ 411093 };
	inline constexpr REL::ID NiRTTI_NiPSysMeshEmitter{ 411094 };
	inline constexpr REL::ID NiRTTI_NiPSysMeshUpdateModifier{ 411060 };
	inline constexpr REL::ID NiRTTI_NiPSysModifier{ 411059 };
	inline constexpr REL::ID NiRTTI_NiPSysModifierActiveCtlr{ 411099 };
	inline constexpr REL::ID NiRTTI_NiPSysModifierBoolCtlr{ 411117 };
	inline constexpr REL::ID NiRTTI_NiPSysModifierCtlr{ 411057 };
	inline constexpr REL::ID NiRTTI_NiPSysModifierFloatCtlr{ 411115 };
	inline constexpr REL::ID NiRTTI_NiPSysPlanarCollider{ 411100 };
	inline constexpr REL::ID NiRTTI_NiPSysPositionModifier{ 411101 };
	inline constexpr REL::ID NiRTTI_NiPSysRadialFieldModifier{ 411102 };
	inline constexpr REL::ID NiRTTI_NiPSysResetOnLoopCtlr{ 411103 };
	inline constexpr REL::ID NiRTTI_NiPSysRotationModifier{ 411104 };
	inline constexpr REL::ID NiRTTI_NiPSysSpawnModifier{ 411105 };
	inline constexpr REL::ID NiRTTI_NiPSysSphereEmitter{ 411106 };
	inline constexpr REL::ID NiRTTI_NiPSysSphericalCollider{ 411107 };
	inline constexpr REL::ID NiRTTI_NiPSysTurbulenceFieldModifier{ 411108 };
	inline constexpr REL::ID NiRTTI_NiPSysUpdateCtlr{ 411061 };
	inline constexpr REL::ID NiRTTI_NiPSysVolumeEmitter{ 411114 };
	inline constexpr REL::ID NiRTTI_NiPSysVortexFieldModifier{ 411109 };
	inline constexpr REL::ID NiRTTI_NiParticleMeshes{ 410586 };
	inline constexpr REL::ID NiRTTI_NiParticleMeshesData{ 410585 };
	inline constexpr REL::ID NiRTTI_NiParticleSystem{ 411046 };
	inline constexpr REL::ID NiRTTI_NiParticles{ 410543 };
	inline constexpr REL::ID NiRTTI_NiParticlesData{ 410584 };
	inline constexpr REL::ID NiRTTI_NiPathController{ 410986 };
	inline constexpr REL::ID NiRTTI_NiPathInterpolator{ 410925 };
	inline constexpr REL::ID NiRTTI_NiPoint3InterpController{ 411041 };
	inline constexpr REL::ID NiRTTI_NiPoint3Interpolator{ 410987 };
	inline constexpr REL::ID NiRTTI_NiPointLight{ 410534 };
	inline constexpr REL::ID NiRTTI_NiPosData{ 410959 };
	inline constexpr REL::ID NiRTTI_NiProperty{ 410509 };
	inline constexpr REL::ID NiRTTI_NiQuaternionInterpolator{ 410988 };
	inline constexpr REL::ID NiRTTI_NiRollController{ 410989 };
	inline constexpr REL::ID NiRTTI_NiRotData{ 410990 };
	inline constexpr REL::ID NiRTTI_NiSequence{ 410991 };
	inline constexpr REL::ID NiRTTI_NiSequenceStreamHelper{ 410994 };
	inline constexpr REL::ID NiRTTI_NiShadeProperty{ 410567 };
	inline constexpr REL::ID NiRTTI_NiSingleInterpController{ 410923 };
	inline constexpr REL::ID NiRTTI_NiSkinData{ 410566 };
	inline constexpr REL::ID NiRTTI_NiSkinInstance{ 410556 };
	inline constexpr REL::ID NiRTTI_NiSkinPartition{ 410554 };
	inline constexpr REL::ID NiRTTI_NiSourceTexture{ 410519 };
	inline constexpr REL::ID NiRTTI_NiSpotLight{ 410587 };
	inline constexpr REL::ID NiRTTI_NiStringExtraData{ 410522 };
	inline constexpr REL::ID NiRTTI_NiStringPalette{ 410995 };
	inline constexpr REL::ID NiRTTI_NiStringsExtraData{ 410505 };
	inline constexpr REL::ID NiRTTI_NiSwitchNode{ 410504 };
	inline constexpr REL::ID NiRTTI_NiSwitchStringExtraData{ 410588 };
	inline constexpr REL::ID NiRTTI_NiTextKeyExtraData{ 410996 };
	inline constexpr REL::ID NiRTTI_NiTexture{ 410547 };
	inline constexpr REL::ID NiRTTI_NiTimeController{ 410523 };
	inline constexpr REL::ID NiRTTI_NiTransformController{ 410932 };
	inline constexpr REL::ID NiRTTI_NiTransformData{ 410958 };
	inline constexpr REL::ID NiRTTI_NiTransformInterpolator{ 410924 };
	inline constexpr REL::ID NiRTTI_NiTriBasedGeom{ 410607 };
	inline constexpr REL::ID NiRTTI_NiTriBasedGeomData{ 410606 };
	inline constexpr REL::ID NiRTTI_NiTriShape{ 410590 };
	inline constexpr REL::ID NiRTTI_NiTriShapeData{ 410589 };
	inline constexpr REL::ID NiRTTI_NiTriStrips{ 410592 };
	inline constexpr REL::ID NiRTTI_NiTriStripsData{ 410591 };
	inline constexpr REL::ID NiRTTI_NiUVData{ 410997 };
	inline constexpr REL::ID NiRTTI_NiVectorExtraData{ 410593 };
	inline constexpr REL::ID NiRTTI_NiVertWeightsExtraData{ 410555 };
	inline constexpr REL::ID NiRTTI_NiVisController{ 410998 };
	inline constexpr REL::ID NiRTTI_PArrayPoint{ 411242 };
	inline constexpr REL::ID NiRTTI_REFRSyncController{ 401106 };
	inline constexpr REL::ID NiRTTI_ReferenceEffect{ 402952 };
	inline constexpr REL::ID NiRTTI_SceneGraph{ 403753 };
	inline constexpr REL::ID NiRTTI_ShaderReferenceEffect{ 402958 };
	inline constexpr REL::ID NiRTTI_ShadowSceneNode{ 414664 };
	inline constexpr REL::ID NiRTTI_SummonPlacementEffect{ 402966 };
	inline constexpr REL::ID NiRTTI_WeaponObject{ 411577 };
	inline constexpr REL::ID NiRTTI_bhkAabbPhantom{ 411596 };
	inline constexpr REL::ID NiRTTI_bhkAction{ 411637 };
	inline constexpr REL::ID NiRTTI_bhkAngularDashpotAction{ 411719 };
	inline constexpr REL::ID NiRTTI_bhkAttachmentCollisionObject{ 411576 };
	inline constexpr REL::ID NiRTTI_bhkAutoWater{ 402390 };
	inline constexpr REL::ID NiRTTI_bhkAvoidBox{ 411625 };
	inline constexpr REL::ID NiRTTI_bhkBallAndSocketConstraint{ 411699 };
	inline constexpr REL::ID NiRTTI_bhkBallSocketConstraintChain{ 411701 };
	inline constexpr REL::ID NiRTTI_bhkBinaryAction{ 411936 };
	inline constexpr REL::ID NiRTTI_bhkBlendCollisionObject{ 411622 };
	inline constexpr REL::ID NiRTTI_bhkBlendController{ 411731 };
	inline constexpr REL::ID NiRTTI_bhkBoxShape{ 411611 };
	inline constexpr REL::ID NiRTTI_bhkBreakableConstraint{ 411717 };
	inline constexpr REL::ID NiRTTI_bhkBvTreeShape{ 411615 };
	inline constexpr REL::ID NiRTTI_bhkCachingShapePhantom{ 411653 };
	inline constexpr REL::ID NiRTTI_bhkCapsuleShape{ 411609 };
	inline constexpr REL::ID NiRTTI_bhkCartTether{ 401566 };
	inline constexpr REL::ID NiRTTI_bhkCharControllerShape{ 411737 };
	inline constexpr REL::ID NiRTTI_bhkCharacterProxy{ 411921 };
	inline constexpr REL::ID NiRTTI_bhkCharacterRigidBody{ 411923 };
	inline constexpr REL::ID NiRTTI_bhkCollisionBox{ 411739 };
	inline constexpr REL::ID NiRTTI_bhkCollisionObject{ 411547 };
	inline constexpr REL::ID NiRTTI_bhkCompressedMeshShape{ 411674 };
	inline constexpr REL::ID NiRTTI_bhkCompressedMeshShapeData{ 411675 };
	inline constexpr REL::ID NiRTTI_bhkConstraint{ 411633 };
	inline constexpr REL::ID NiRTTI_bhkConstraintChain{ 411934 };
	inline constexpr REL::ID NiRTTI_bhkConvexShape{ 411601 };
	inline constexpr REL::ID NiRTTI_bhkConvexSweepShape{ 411677 };
	inline constexpr REL::ID NiRTTI_bhkConvexTransformShape{ 411679 };
	inline constexpr REL::ID NiRTTI_bhkConvexTranslateShape{ 411681 };
	inline constexpr REL::ID NiRTTI_bhkConvexVerticesShape{ 411683 };
	inline constexpr REL::ID NiRTTI_bhkCylinderShape{ 411685 };
	inline constexpr REL::ID NiRTTI_bhkDashpotAction{ 411721 };
	inline constexpr REL::ID NiRTTI_bhkEntity{ 411592 };
	inline constexpr REL::ID NiRTTI_bhkExtraData{ 411732 };
	inline constexpr REL::ID NiRTTI_bhkFixedConstraint{ 411707 };
	inline constexpr REL::ID NiRTTI_bhkGenericConstraint{ 411736 };
	inline constexpr REL::ID NiRTTI_bhkGroupConstraint{ 411703 };
	inline constexpr REL::ID NiRTTI_bhkHeightFieldShape{ 411932 };
	inline constexpr REL::ID NiRTTI_bhkHingeConstraint{ 411663 };
	inline constexpr REL::ID NiRTTI_bhkHingeLimitsConstraint{ 411705 };
	inline constexpr REL::ID NiRTTI_bhkLimitedHingeConstraint{ 411627 };
	inline constexpr REL::ID NiRTTI_bhkLiquidAction{ 411723 };
	inline constexpr REL::ID NiRTTI_bhkListShape{ 411697 };
	inline constexpr REL::ID NiRTTI_bhkMalleableConstraint{ 411629 };
	inline constexpr REL::ID NiRTTI_bhkMoppBvTreeShape{ 411693 };
	inline constexpr REL::ID NiRTTI_bhkMotorAction{ 411726 };
	inline constexpr REL::ID NiRTTI_bhkMouseSpringAction{ 411661 };
	inline constexpr REL::ID NiRTTI_bhkMultiSphereShape{ 411687 };
	inline constexpr REL::ID NiRTTI_bhkNiCollisionObject{ 411565 };
	inline constexpr REL::ID NiRTTI_bhkNiTriStripsShape{ 411617 };
	inline constexpr REL::ID NiRTTI_bhkOrientHingedBodyAction{ 411728 };
	inline constexpr REL::ID NiRTTI_bhkPCollisionObject{ 411602 };
	inline constexpr REL::ID NiRTTI_bhkPackedNiTriStripsShape{ 411620 };
	inline constexpr REL::ID NiRTTI_bhkPhantom{ 411594 };
	inline constexpr REL::ID NiRTTI_bhkPlaneShape{ 411689 };
	inline constexpr REL::ID NiRTTI_bhkPointToPathConstraint{ 411942 };
	inline constexpr REL::ID NiRTTI_bhkPoseArray{ 411733 };
	inline constexpr REL::ID NiRTTI_bhkPositionConstraintMotor{ 411743 };
	inline constexpr REL::ID NiRTTI_bhkPrismaticConstraint{ 411635 };
	inline constexpr REL::ID NiRTTI_bhkRagdollConstraint{ 411709 };
	inline constexpr REL::ID NiRTTI_bhkRagdollLimitsConstraint{ 411711 };
	inline constexpr REL::ID NiRTTI_bhkRagdollTemplate{ 411658 };
	inline constexpr REL::ID NiRTTI_bhkRagdollTemplateData{ 411657 };
	inline constexpr REL::ID NiRTTI_bhkRefObject{ 411583 };
	inline constexpr REL::ID NiRTTI_bhkRigidBody{ 411544 };
	inline constexpr REL::ID NiRTTI_bhkRigidBodyT{ 411581 };
	inline constexpr REL::ID NiRTTI_bhkSPCollisionObject{ 411659 };
	inline constexpr REL::ID NiRTTI_bhkSerializable{ 411584 };
	inline constexpr REL::ID NiRTTI_bhkShape{ 411590 };
	inline constexpr REL::ID NiRTTI_bhkShapeCollection{ 411741 };
	inline constexpr REL::ID NiRTTI_bhkShapePhantom{ 411605 };
	inline constexpr REL::ID NiRTTI_bhkSimpleShapePhantom{ 411607 };
	inline constexpr REL::ID NiRTTI_bhkSphereRepShape{ 411598 };
	inline constexpr REL::ID NiRTTI_bhkSphereShape{ 411613 };
	inline constexpr REL::ID NiRTTI_bhkSpringAction{ 411730 };
	inline constexpr REL::ID NiRTTI_bhkSpringDamperConstraintMotor{ 411745 };
	inline constexpr REL::ID NiRTTI_bhkStiffSpringConstraint{ 411713 };
	inline constexpr REL::ID NiRTTI_bhkTiltPreventAction{ 401567 };
	inline constexpr REL::ID NiRTTI_bhkTransformShape{ 411695 };
	inline constexpr REL::ID NiRTTI_bhkTriSampledHeightFieldBvTreeShape{ 411639 };
	inline constexpr REL::ID NiRTTI_bhkTriangleShape{ 411691 };
	inline constexpr REL::ID NiRTTI_bhkUnaryAction{ 411631 };
	inline constexpr REL::ID NiRTTI_bhkVelocityConstraintMotor{ 411744 };
	inline constexpr REL::ID NiRTTI_bhkWheelAction{ 401568 };
	inline constexpr REL::ID NiRTTI_bhkWheelConstraint{ 411715 };
	inline constexpr REL::ID NiRTTI_bhkWorld{ 411527 };
	inline constexpr REL::ID NiRTTI_bhkWorldM{ 411582 };
	inline constexpr REL::ID NiRTTI_bhkWorldObject{ 411515 };
	inline constexpr REL::ID NiRTTI_hkPackedNiTriStripsData{ 411603 };
#else
	inline constexpr REL::ID NiRTTI_BGSAddonNodeSoundHandleExtra(static_cast<std::uint64_t>(514633));
	inline constexpr REL::ID NiRTTI_BGSDecalNode(static_cast<std::uint64_t>(514417));
	inline constexpr REL::ID NiRTTI_BSAnimGroupSequence(static_cast<std::uint64_t>(514462));
	inline constexpr REL::ID NiRTTI_BSAnimInteractionMarker(static_cast<std::uint64_t>(524679));
	inline constexpr REL::ID NiRTTI_BSAnimNote(static_cast<std::uint64_t>(524418));
	inline constexpr REL::ID NiRTTI_BSAnimNotes(static_cast<std::uint64_t>(524419));
	inline constexpr REL::ID NiRTTI_BSBehaviorGraphExtraData(static_cast<std::uint64_t>(524621));
	inline constexpr REL::ID NiRTTI_BSBlastNode(static_cast<std::uint64_t>(524598));
	inline constexpr REL::ID NiRTTI_BSBlendTreadTransfInterpolator(static_cast<std::uint64_t>(524358));
	inline constexpr REL::ID NiRTTI_BSBloodSplatterShaderProperty(static_cast<std::uint64_t>(527906));
	inline constexpr REL::ID NiRTTI_BSBodyMorphOffsetsExtraData(static_cast<std::uint64_t>(524620));
	inline constexpr REL::ID NiRTTI_BSBoneLODExtraData(static_cast<std::uint64_t>(524706));
	inline constexpr REL::ID NiRTTI_BSBoneMap(static_cast<std::uint64_t>(524677));
	inline constexpr REL::ID NiRTTI_BSBound(static_cast<std::uint64_t>(524648));
	inline constexpr REL::ID NiRTTI_BSClearZNode(static_cast<std::uint64_t>(528336));
	inline constexpr REL::ID NiRTTI_BSCubeMapCamera(static_cast<std::uint64_t>(528279));
	inline constexpr REL::ID NiRTTI_BSCullingProcess(static_cast<std::uint64_t>(524626));
	inline constexpr REL::ID NiRTTI_BSDamageStage(static_cast<std::uint64_t>(524600));
	inline constexpr REL::ID NiRTTI_BSDebrisNode(static_cast<std::uint64_t>(524599));
	inline constexpr REL::ID NiRTTI_BSDecalPlacementVectorExtraData(static_cast<std::uint64_t>(524710));
	inline constexpr REL::ID NiRTTI_BSDismemberSkinInstance(static_cast<std::uint64_t>(523941));
	inline constexpr REL::ID NiRTTI_BSDistantObjectLargeRefExtraData(static_cast<std::uint64_t>(524689));
	inline constexpr REL::ID NiRTTI_BSDistantTreeShaderProperty(static_cast<std::uint64_t>(528220));
	inline constexpr REL::ID NiRTTI_BSDoorHavokController(static_cast<std::uint64_t>(517601));
	inline constexpr REL::ID NiRTTI_BSDynamicLines(static_cast<std::uint64_t>(528362));
	inline constexpr REL::ID NiRTTI_BSDynamicTriShape(static_cast<std::uint64_t>(523953));
	inline constexpr REL::ID NiRTTI_BSEffectShaderProperty(static_cast<std::uint64_t>(527834));
	inline constexpr REL::ID NiRTTI_BSEffectShaderPropertyColorController(static_cast<std::uint64_t>(528413));
	inline constexpr REL::ID NiRTTI_BSEffectShaderPropertyFloatController(static_cast<std::uint64_t>(528411));
	inline constexpr REL::ID NiRTTI_BSFaceGenAnimationData(static_cast<std::uint64_t>(515540));
	inline constexpr REL::ID NiRTTI_BSFaceGenBaseMorphExtraData(static_cast<std::uint64_t>(515562));
	inline constexpr REL::ID NiRTTI_BSFaceGenModelExtraData(static_cast<std::uint64_t>(515558));
	inline constexpr REL::ID NiRTTI_BSFaceGenMorphData(static_cast<std::uint64_t>(515563));
	inline constexpr REL::ID NiRTTI_BSFaceGenMorphDataHair(static_cast<std::uint64_t>(515565));
	inline constexpr REL::ID NiRTTI_BSFaceGenMorphDataHead(static_cast<std::uint64_t>(515564));
	inline constexpr REL::ID NiRTTI_BSFaceGenNiNode(static_cast<std::uint64_t>(515572));
	inline constexpr REL::ID NiRTTI_BSFadeNode(static_cast<std::uint64_t>(527630));
	inline constexpr REL::ID NiRTTI_BSFadeNodeCuller(static_cast<std::uint64_t>(528214));
	inline constexpr REL::ID NiRTTI_BSFlattenedBoneTree(static_cast<std::uint64_t>(523940));
	inline constexpr REL::ID NiRTTI_BSFogProperty(static_cast<std::uint64_t>(528312));
	inline constexpr REL::ID NiRTTI_BSFrustumFOVController(static_cast<std::uint64_t>(524424));
	inline constexpr REL::ID NiRTTI_BSFurnitureMarkerNode(static_cast<std::uint64_t>(524633));
	inline constexpr REL::ID NiRTTI_BSGeometry(static_cast<std::uint64_t>(523951));
	inline constexpr REL::ID NiRTTI_BSGeometryListCullingProcess(static_cast<std::uint64_t>(524686));
	inline constexpr REL::ID NiRTTI_BSGrabIKNote(static_cast<std::uint64_t>(524420));
	inline constexpr REL::ID NiRTTI_BSGrassShaderProperty(static_cast<std::uint64_t>(527760));
	inline constexpr REL::ID NiRTTI_BSInstanceTriShape(static_cast<std::uint64_t>(524722));
	inline constexpr REL::ID NiRTTI_BSInvMarker(static_cast<std::uint64_t>(524704));
	inline constexpr REL::ID NiRTTI_BSLODMultiIndexTriShape(static_cast<std::uint64_t>(528536));
	inline constexpr REL::ID NiRTTI_BSLODTriShape(static_cast<std::uint64_t>(524017));
	inline constexpr REL::ID NiRTTI_BSLagBoneController(static_cast<std::uint64_t>(524718));
	inline constexpr REL::ID NiRTTI_BSLeafAnimNode(static_cast<std::uint64_t>(527635));
	inline constexpr REL::ID NiRTTI_BSLightingShaderProperty(static_cast<std::uint64_t>(527752));
	inline constexpr REL::ID NiRTTI_BSLightingShaderPropertyColorController(static_cast<std::uint64_t>(528400));
	inline constexpr REL::ID NiRTTI_BSLightingShaderPropertyFloatController(static_cast<std::uint64_t>(528394));
	inline constexpr REL::ID NiRTTI_BSLightingShaderPropertyUShortController(static_cast<std::uint64_t>(528397));
	inline constexpr REL::ID NiRTTI_BSLines(static_cast<std::uint64_t>(528361));
	inline constexpr REL::ID NiRTTI_BSLookIKNote(static_cast<std::uint64_t>(524421));
	inline constexpr REL::ID NiRTTI_BSMasterParticleSystem(static_cast<std::uint64_t>(524698));
	inline constexpr REL::ID NiRTTI_BSMeshLODTriShape(static_cast<std::uint64_t>(528535));
	inline constexpr REL::ID NiRTTI_BSMultiBound(static_cast<std::uint64_t>(524551));
	inline constexpr REL::ID NiRTTI_BSMultiBoundAABB(static_cast<std::uint64_t>(524554));
	inline constexpr REL::ID NiRTTI_BSMultiBoundCapsule(static_cast<std::uint64_t>(524714));
	inline constexpr REL::ID NiRTTI_BSMultiBoundNode(static_cast<std::uint64_t>(524676));
	inline constexpr REL::ID NiRTTI_BSMultiBoundOBB(static_cast<std::uint64_t>(524556));
	inline constexpr REL::ID NiRTTI_BSMultiBoundRoom(static_cast<std::uint64_t>(524552));
	inline constexpr REL::ID NiRTTI_BSMultiBoundShape(static_cast<std::uint64_t>(524611));
	inline constexpr REL::ID NiRTTI_BSMultiBoundSphere(static_cast<std::uint64_t>(524612));
	inline constexpr REL::ID NiRTTI_BSMultiIndexTriShape(static_cast<std::uint64_t>(528364));
	inline constexpr REL::ID NiRTTI_BSMultiStreamInstanceTriShape(static_cast<std::uint64_t>(524606));
	inline constexpr REL::ID NiRTTI_BSMultiTargetTreadTransfController(static_cast<std::uint64_t>(524062));
	inline constexpr REL::ID NiRTTI_BSNiAlphaPropertyTestRefController(static_cast<std::uint64_t>(528414));
	inline constexpr REL::ID NiRTTI_BSNiNode(static_cast<std::uint64_t>(524721));
	inline constexpr REL::ID NiRTTI_BSNodeReferences(static_cast<std::uint64_t>(524709));
	inline constexpr REL::ID NiRTTI_BSNonUniformScaleExtraData(static_cast<std::uint64_t>(524719));
	inline constexpr REL::ID NiRTTI_BSOcclusionBox(static_cast<std::uint64_t>(524614));
	inline constexpr REL::ID NiRTTI_BSOcclusionPlane(static_cast<std::uint64_t>(524616));
	inline constexpr REL::ID NiRTTI_BSOcclusionShape(static_cast<std::uint64_t>(524577));
	inline constexpr REL::ID NiRTTI_BSOrderedNode(static_cast<std::uint64_t>(528360));
	inline constexpr REL::ID NiRTTI_BSPSysArrayEmitter(static_cast<std::uint64_t>(524601));
	inline constexpr REL::ID NiRTTI_BSPSysHavokUpdateModifier(static_cast<std::uint64_t>(524468));
	inline constexpr REL::ID NiRTTI_BSPSysInheritVelocityModifier(static_cast<std::uint64_t>(524534));
	inline constexpr REL::ID NiRTTI_BSPSysLODModifier(static_cast<std::uint64_t>(528416));
	inline constexpr REL::ID NiRTTI_BSPSysMultiTargetEmitterCtlr(static_cast<std::uint64_t>(524684));
	inline constexpr REL::ID NiRTTI_BSPSysRecycleBoundModifier(static_cast<std::uint64_t>(524533));
	inline constexpr REL::ID NiRTTI_BSPSysScaleModifier(static_cast<std::uint64_t>(524717));
	inline constexpr REL::ID NiRTTI_BSPSysSimpleColorModifier(static_cast<std::uint64_t>(528415));
	inline constexpr REL::ID NiRTTI_BSPSysStripUpdateModifier(static_cast<std::uint64_t>(524715));
	inline constexpr REL::ID NiRTTI_BSPSysSubTexModifier(static_cast<std::uint64_t>(524716));
	inline constexpr REL::ID NiRTTI_BSParabolicCullingProcess(static_cast<std::uint64_t>(528534));
	inline constexpr REL::ID NiRTTI_BSParentVelocityModifier(static_cast<std::uint64_t>(524711));
	inline constexpr REL::ID NiRTTI_BSParticleShaderProperty(static_cast<std::uint64_t>(527992));
	inline constexpr REL::ID NiRTTI_BSParticleSystemManager(static_cast<std::uint64_t>(524629));
	inline constexpr REL::ID NiRTTI_BSPlayerDistanceCheckController(static_cast<std::uint64_t>(517602));
	inline constexpr REL::ID NiRTTI_BSPortal(static_cast<std::uint64_t>(524617));
	inline constexpr REL::ID NiRTTI_BSPortalSharedNode(static_cast<std::uint64_t>(524618));
	inline constexpr REL::ID NiRTTI_BSProceduralLightningController(static_cast<std::uint64_t>(524703));
	inline constexpr REL::ID NiRTTI_BSRangeNode(static_cast<std::uint64_t>(524594));
	inline constexpr REL::ID NiRTTI_BSReference(static_cast<std::uint64_t>(524708));
	inline constexpr REL::ID NiRTTI_BSRotAccumTransfInterpolator(static_cast<std::uint64_t>(524422));
	inline constexpr REL::ID NiRTTI_BSSceneGraph(static_cast<std::uint64_t>(524681));
	inline constexpr REL::ID NiRTTI_BSSegmentedTriShape(static_cast<std::uint64_t>(524019));
	inline constexpr REL::ID NiRTTI_BSShaderAccumulator(static_cast<std::uint64_t>(527798));
	inline constexpr REL::ID NiRTTI_BSShaderProperty(static_cast<std::uint64_t>(527634));
	inline constexpr REL::ID NiRTTI_BSShaderTextureSet(static_cast<std::uint64_t>(528104));
	inline constexpr REL::ID NiRTTI_BSSimpleScaleController(static_cast<std::uint64_t>(517603));
	inline constexpr REL::ID NiRTTI_BSSkyShaderProperty(static_cast<std::uint64_t>(528205));
	inline constexpr REL::ID NiRTTI_BSSplatterExtraData(static_cast<std::uint64_t>(514508));
	inline constexpr REL::ID NiRTTI_BSStripPSysData(static_cast<std::uint64_t>(524531));
	inline constexpr REL::ID NiRTTI_BSStripParticleSystem(static_cast<std::uint64_t>(524474));
	inline constexpr REL::ID NiRTTI_BSSubIndexLandTriShape(static_cast<std::uint64_t>(528538));
	inline constexpr REL::ID NiRTTI_BSSubIndexTriShape(static_cast<std::uint64_t>(524688));
	inline constexpr REL::ID NiRTTI_BSTempEffect(static_cast<std::uint64_t>(515912));
	inline constexpr REL::ID NiRTTI_BSTempEffectDebris(static_cast<std::uint64_t>(515921));
	inline constexpr REL::ID NiRTTI_BSTempEffectGeometryDecal(static_cast<std::uint64_t>(515924));
	inline constexpr REL::ID NiRTTI_BSTempEffectParticle(static_cast<std::uint64_t>(515935));
	inline constexpr REL::ID NiRTTI_BSTempEffectSPG(static_cast<std::uint64_t>(515940));
	inline constexpr REL::ID NiRTTI_BSTempEffectSimpleDecal(static_cast<std::uint64_t>(515938));
	inline constexpr REL::ID NiRTTI_BSTempNode(static_cast<std::uint64_t>(524573));
	inline constexpr REL::ID NiRTTI_BSTempNodeManager(static_cast<std::uint64_t>(524572));
	inline constexpr REL::ID NiRTTI_BSTextureSet(static_cast<std::uint64_t>(528103));
	inline constexpr REL::ID NiRTTI_BSTreadTransfInterpolator(static_cast<std::uint64_t>(524423));
	inline constexpr REL::ID NiRTTI_BSTreeNode(static_cast<std::uint64_t>(527636));
	inline constexpr REL::ID NiRTTI_BSTriShape(static_cast<std::uint64_t>(523928));
	inline constexpr REL::ID NiRTTI_BSValueNode(static_cast<std::uint64_t>(524560));
	inline constexpr REL::ID NiRTTI_BSWArray(static_cast<std::uint64_t>(524712));
	inline constexpr REL::ID NiRTTI_BSWaterShaderProperty(static_cast<std::uint64_t>(527905));
	inline constexpr REL::ID NiRTTI_BSWindModifier(static_cast<std::uint64_t>(524568));
	inline constexpr REL::ID NiRTTI_BSXFlags(static_cast<std::uint64_t>(524558));
	inline constexpr REL::ID NiRTTI_DebugTextExtraData(static_cast<std::uint64_t>(525589));
	inline constexpr REL::ID NiRTTI_ModelReferenceEffect(static_cast<std::uint64_t>(516697));
	inline constexpr REL::ID NiRTTI_NiAVObject(static_cast<std::uint64_t>(523895));
	inline constexpr REL::ID NiRTTI_NiAVObjectPalette(static_cast<std::uint64_t>(523977));
	inline constexpr REL::ID NiRTTI_NiAccumulator(static_cast<std::uint64_t>(524024));
	inline constexpr REL::ID NiRTTI_NiAdditionalGeometryData(static_cast<std::uint64_t>(524018));
	inline constexpr REL::ID NiRTTI_NiAlphaAccumulator(static_cast<std::uint64_t>(523989));
	inline constexpr REL::ID NiRTTI_NiAlphaProperty(static_cast<std::uint64_t>(523931));
	inline constexpr REL::ID NiRTTI_NiAmbientLight(static_cast<std::uint64_t>(523990));
	inline constexpr REL::ID NiRTTI_NiBSBoneLODController(static_cast<std::uint64_t>(524623));
	inline constexpr REL::ID NiRTTI_NiBSPNode(static_cast<std::uint64_t>(523993));
	inline constexpr REL::ID NiRTTI_NiBSplineBasisData(static_cast<std::uint64_t>(524386));
	inline constexpr REL::ID NiRTTI_NiBSplineColorInterpolator(static_cast<std::uint64_t>(524388));
	inline constexpr REL::ID NiRTTI_NiBSplineCompColorInterpolator(static_cast<std::uint64_t>(524389));
	inline constexpr REL::ID NiRTTI_NiBSplineCompFloatInterpolator(static_cast<std::uint64_t>(524390));
	inline constexpr REL::ID NiRTTI_NiBSplineCompPoint3Interpolator(static_cast<std::uint64_t>(524391));
	inline constexpr REL::ID NiRTTI_NiBSplineCompTransformInterpolator(static_cast<std::uint64_t>(524392));
	inline constexpr REL::ID NiRTTI_NiBSplineData(static_cast<std::uint64_t>(524387));
	inline constexpr REL::ID NiRTTI_NiBSplineFloatInterpolator(static_cast<std::uint64_t>(524393));
	inline constexpr REL::ID NiRTTI_NiBSplineInterpolator(static_cast<std::uint64_t>(524459));
	inline constexpr REL::ID NiRTTI_NiBSplinePoint3Interpolator(static_cast<std::uint64_t>(524394));
	inline constexpr REL::ID NiRTTI_NiBSplineTransformInterpolator(static_cast<std::uint64_t>(524395));
	inline constexpr REL::ID NiRTTI_NiBackToFrontAccumulator(static_cast<std::uint64_t>(524025));
	inline constexpr REL::ID NiRTTI_NiBillboardNode(static_cast<std::uint64_t>(523959));
	inline constexpr REL::ID NiRTTI_NiBinaryExtraData(static_cast<std::uint64_t>(523991));
	inline constexpr REL::ID NiRTTI_NiBlendAccumTransformInterpolator(static_cast<std::uint64_t>(524352));
	inline constexpr REL::ID NiRTTI_NiBlendBoolInterpolator(static_cast<std::uint64_t>(524379));
	inline constexpr REL::ID NiRTTI_NiBlendColorInterpolator(static_cast<std::uint64_t>(524380));
	inline constexpr REL::ID NiRTTI_NiBlendFloatInterpolator(static_cast<std::uint64_t>(524349));
	inline constexpr REL::ID NiRTTI_NiBlendInterpolator(static_cast<std::uint64_t>(524060));
	inline constexpr REL::ID NiRTTI_NiBlendPoint3Interpolator(static_cast<std::uint64_t>(524381));
	inline constexpr REL::ID NiRTTI_NiBlendQuaternionInterpolator(static_cast<std::uint64_t>(524382));
	inline constexpr REL::ID NiRTTI_NiBlendTransformInterpolator(static_cast<std::uint64_t>(524348));
	inline constexpr REL::ID NiRTTI_NiBoolData(static_cast<std::uint64_t>(524383));
	inline constexpr REL::ID NiRTTI_NiBoolInterpController(static_cast<std::uint64_t>(524463));
	inline constexpr REL::ID NiRTTI_NiBoolInterpolator(static_cast<std::uint64_t>(524384));
	inline constexpr REL::ID NiRTTI_NiBoolTimelineInterpolator(static_cast<std::uint64_t>(524385));
	inline constexpr REL::ID NiRTTI_NiBooleanExtraData(static_cast<std::uint64_t>(523992));
	inline constexpr REL::ID NiRTTI_NiCamera(static_cast<std::uint64_t>(523926));
	inline constexpr REL::ID NiRTTI_NiCollisionData(static_cast<std::uint64_t>(524035));
	inline constexpr REL::ID NiRTTI_NiCollisionObject(static_cast<std::uint64_t>(528359));
	inline constexpr REL::ID NiRTTI_NiColorData(static_cast<std::uint64_t>(524340));
	inline constexpr REL::ID NiRTTI_NiColorExtraData(static_cast<std::uint64_t>(523994));
	inline constexpr REL::ID NiRTTI_NiColorExtraDataController(static_cast<std::uint64_t>(524396));
	inline constexpr REL::ID NiRTTI_NiColorInterpolator(static_cast<std::uint64_t>(524341));
	inline constexpr REL::ID NiRTTI_NiControllerManager(static_cast<std::uint64_t>(524054));
	inline constexpr REL::ID NiRTTI_NiControllerSequence(static_cast<std::uint64_t>(524057));
	inline constexpr REL::ID NiRTTI_NiCullingProcess(static_cast<std::uint64_t>(523961));
	inline constexpr REL::ID NiRTTI_NiDefaultAVObjectPalette(static_cast<std::uint64_t>(523955));
	inline constexpr REL::ID NiRTTI_NiDirectionalLight(static_cast<std::uint64_t>(523960));
	inline constexpr REL::ID NiRTTI_NiExtraData(static_cast<std::uint64_t>(523948));
	inline constexpr REL::ID NiRTTI_NiExtraDataController(static_cast<std::uint64_t>(524458));
	inline constexpr REL::ID NiRTTI_NiFloatController(static_cast<std::uint64_t>(524462));
	inline constexpr REL::ID NiRTTI_NiFloatData(static_cast<std::uint64_t>(524338));
	inline constexpr REL::ID NiRTTI_NiFloatExtraData(static_cast<std::uint64_t>(523995));
	inline constexpr REL::ID NiRTTI_NiFloatExtraDataController(static_cast<std::uint64_t>(524350));
	inline constexpr REL::ID NiRTTI_NiFloatInterpController(static_cast<std::uint64_t>(524461));
	inline constexpr REL::ID NiRTTI_NiFloatInterpolator(static_cast<std::uint64_t>(524339));
	inline constexpr REL::ID NiRTTI_NiFloatsExtraData(static_cast<std::uint64_t>(523996));
	inline constexpr REL::ID NiRTTI_NiFloatsExtraDataController(static_cast<std::uint64_t>(524397));
	inline constexpr REL::ID NiRTTI_NiFloatsExtraDataPoint3Controller(static_cast<std::uint64_t>(524398));
	inline constexpr REL::ID NiRTTI_NiFogProperty(static_cast<std::uint64_t>(523997));
	inline constexpr REL::ID NiRTTI_NiGeometry(static_cast<std::uint64_t>(523978));
	inline constexpr REL::ID NiRTTI_NiGeometryData(static_cast<std::uint64_t>(523949));
	inline constexpr REL::ID NiRTTI_NiIntegerExtraData(static_cast<std::uint64_t>(523999));
	inline constexpr REL::ID NiRTTI_NiIntegersExtraData(static_cast<std::uint64_t>(524000));
	inline constexpr REL::ID NiRTTI_NiInterpController(static_cast<std::uint64_t>(524063));
	inline constexpr REL::ID NiRTTI_NiInterpolator(static_cast<std::uint64_t>(524353));
	inline constexpr REL::ID NiRTTI_NiKeyBasedInterpolator(static_cast<std::uint64_t>(524361));
	inline constexpr REL::ID NiRTTI_NiKeyframeManager(static_cast<std::uint64_t>(524399));
	inline constexpr REL::ID NiRTTI_NiLight(static_cast<std::uint64_t>(523923));
	inline constexpr REL::ID NiRTTI_NiLightColorController(static_cast<std::uint64_t>(524400));
	inline constexpr REL::ID NiRTTI_NiLightDimmerController(static_cast<std::uint64_t>(524401));
	inline constexpr REL::ID NiRTTI_NiLookAtController(static_cast<std::uint64_t>(524402));
	inline constexpr REL::ID NiRTTI_NiLookAtInterpolator(static_cast<std::uint64_t>(524403));
	inline constexpr REL::ID NiRTTI_NiMeshPSysData(static_cast<std::uint64_t>(524481));
	inline constexpr REL::ID NiRTTI_NiMeshParticleSystem(static_cast<std::uint64_t>(524470));
	inline constexpr REL::ID NiRTTI_NiMorphData(static_cast<std::uint64_t>(524404));
	inline constexpr REL::ID NiRTTI_NiMultiTargetTransformController(static_cast<std::uint64_t>(524061));
	inline constexpr REL::ID NiRTTI_NiNode(static_cast<std::uint64_t>(523900));
	inline constexpr REL::ID NiRTTI_NiObject(static_cast<std::uint64_t>(523891));
	inline constexpr REL::ID NiRTTI_NiObjectNET(static_cast<std::uint64_t>(523910));
	inline constexpr REL::ID NiRTTI_NiPSysAgeDeathModifier(static_cast<std::uint64_t>(524486));
	inline constexpr REL::ID NiRTTI_NiPSysAirFieldAirFrictionCtlr(static_cast<std::uint64_t>(524482));
	inline constexpr REL::ID NiRTTI_NiPSysAirFieldInheritVelocityCtlr(static_cast<std::uint64_t>(524483));
	inline constexpr REL::ID NiRTTI_NiPSysAirFieldModifier(static_cast<std::uint64_t>(524484));
	inline constexpr REL::ID NiRTTI_NiPSysAirFieldSpreadCtlr(static_cast<std::uint64_t>(524485));
	inline constexpr REL::ID NiRTTI_NiPSysBombModifier(static_cast<std::uint64_t>(524487));
	inline constexpr REL::ID NiRTTI_NiPSysBoundUpdateModifier(static_cast<std::uint64_t>(524488));
	inline constexpr REL::ID NiRTTI_NiPSysBoxEmitter(static_cast<std::uint64_t>(524489));
	inline constexpr REL::ID NiRTTI_NiPSysCollider(static_cast<std::uint64_t>(524539));
	inline constexpr REL::ID NiRTTI_NiPSysColliderManager(static_cast<std::uint64_t>(524490));
	inline constexpr REL::ID NiRTTI_NiPSysColorModifier(static_cast<std::uint64_t>(524491));
	inline constexpr REL::ID NiRTTI_NiPSysCylinderEmitter(static_cast<std::uint64_t>(524473));
	inline constexpr REL::ID NiRTTI_NiPSysData(static_cast<std::uint64_t>(524492));
	inline constexpr REL::ID NiRTTI_NiPSysDragFieldModifier(static_cast<std::uint64_t>(524493));
	inline constexpr REL::ID NiRTTI_NiPSysDragModifier(static_cast<std::uint64_t>(524494));
	inline constexpr REL::ID NiRTTI_NiPSysEmitter(static_cast<std::uint64_t>(524475));
	inline constexpr REL::ID NiRTTI_NiPSysEmitterCtlr(static_cast<std::uint64_t>(524466));
	inline constexpr REL::ID NiRTTI_NiPSysEmitterCtlrData(static_cast<std::uint64_t>(524495));
	inline constexpr REL::ID NiRTTI_NiPSysEmitterDeclinationCtlr(static_cast<std::uint64_t>(524496));
	inline constexpr REL::ID NiRTTI_NiPSysEmitterDeclinationVarCtlr(static_cast<std::uint64_t>(524497));
	inline constexpr REL::ID NiRTTI_NiPSysEmitterInitialRadiusCtlr(static_cast<std::uint64_t>(524498));
	inline constexpr REL::ID NiRTTI_NiPSysEmitterLifeSpanCtlr(static_cast<std::uint64_t>(524499));
	inline constexpr REL::ID NiRTTI_NiPSysEmitterPlanarAngleCtlr(static_cast<std::uint64_t>(524500));
	inline constexpr REL::ID NiRTTI_NiPSysEmitterPlanarAngleVarCtlr(static_cast<std::uint64_t>(524501));
	inline constexpr REL::ID NiRTTI_NiPSysEmitterSpeedCtlr(static_cast<std::uint64_t>(524502));
	inline constexpr REL::ID NiRTTI_NiPSysFieldAttenuationCtlr(static_cast<std::uint64_t>(524503));
	inline constexpr REL::ID NiRTTI_NiPSysFieldMagnitudeCtlr(static_cast<std::uint64_t>(524504));
	inline constexpr REL::ID NiRTTI_NiPSysFieldMaxDistanceCtlr(static_cast<std::uint64_t>(524505));
	inline constexpr REL::ID NiRTTI_NiPSysFieldModifier(static_cast<std::uint64_t>(524537));
	inline constexpr REL::ID NiRTTI_NiPSysGravityFieldModifier(static_cast<std::uint64_t>(524506));
	inline constexpr REL::ID NiRTTI_NiPSysGravityModifier(static_cast<std::uint64_t>(524467));
	inline constexpr REL::ID NiRTTI_NiPSysGravityStrengthCtlr(static_cast<std::uint64_t>(524507));
	inline constexpr REL::ID NiRTTI_NiPSysGrowFadeModifier(static_cast<std::uint64_t>(524508));
	inline constexpr REL::ID NiRTTI_NiPSysInitialRotAngleCtlr(static_cast<std::uint64_t>(524509));
	inline constexpr REL::ID NiRTTI_NiPSysInitialRotAngleVarCtlr(static_cast<std::uint64_t>(524510));
	inline constexpr REL::ID NiRTTI_NiPSysInitialRotSpeedCtlr(static_cast<std::uint64_t>(524511));
	inline constexpr REL::ID NiRTTI_NiPSysInitialRotSpeedVarCtlr(static_cast<std::uint64_t>(524512));
	inline constexpr REL::ID NiRTTI_NiPSysMeshEmitter(static_cast<std::uint64_t>(524513));
	inline constexpr REL::ID NiRTTI_NiPSysMeshUpdateModifier(static_cast<std::uint64_t>(524479));
	inline constexpr REL::ID NiRTTI_NiPSysModifier(static_cast<std::uint64_t>(524478));
	inline constexpr REL::ID NiRTTI_NiPSysModifierActiveCtlr(static_cast<std::uint64_t>(524518));
	inline constexpr REL::ID NiRTTI_NiPSysModifierBoolCtlr(static_cast<std::uint64_t>(524538));
	inline constexpr REL::ID NiRTTI_NiPSysModifierCtlr(static_cast<std::uint64_t>(524477));
	inline constexpr REL::ID NiRTTI_NiPSysModifierFloatCtlr(static_cast<std::uint64_t>(524536));
	inline constexpr REL::ID NiRTTI_NiPSysPlanarCollider(static_cast<std::uint64_t>(524519));
	inline constexpr REL::ID NiRTTI_NiPSysPositionModifier(static_cast<std::uint64_t>(524522));
	inline constexpr REL::ID NiRTTI_NiPSysRadialFieldModifier(static_cast<std::uint64_t>(524523));
	inline constexpr REL::ID NiRTTI_NiPSysResetOnLoopCtlr(static_cast<std::uint64_t>(524524));
	inline constexpr REL::ID NiRTTI_NiPSysRotationModifier(static_cast<std::uint64_t>(524525));
	inline constexpr REL::ID NiRTTI_NiPSysSpawnModifier(static_cast<std::uint64_t>(524526));
	inline constexpr REL::ID NiRTTI_NiPSysSphereEmitter(static_cast<std::uint64_t>(524527));
	inline constexpr REL::ID NiRTTI_NiPSysSphericalCollider(static_cast<std::uint64_t>(524528));
	inline constexpr REL::ID NiRTTI_NiPSysTurbulenceFieldModifier(static_cast<std::uint64_t>(524529));
	inline constexpr REL::ID NiRTTI_NiPSysUpdateCtlr(static_cast<std::uint64_t>(524480));
	inline constexpr REL::ID NiRTTI_NiPSysVolumeEmitter(static_cast<std::uint64_t>(524535));
	inline constexpr REL::ID NiRTTI_NiPSysVortexFieldModifier(static_cast<std::uint64_t>(524530));
	inline constexpr REL::ID NiRTTI_NiParticleMeshes(static_cast<std::uint64_t>(524006));
	inline constexpr REL::ID NiRTTI_NiParticleMeshesData(static_cast<std::uint64_t>(524005));
	inline constexpr REL::ID NiRTTI_NiParticleSystem(static_cast<std::uint64_t>(524465));
	inline constexpr REL::ID NiRTTI_NiParticles(static_cast<std::uint64_t>(523963));
	inline constexpr REL::ID NiRTTI_NiParticlesData(static_cast<std::uint64_t>(524004));
	inline constexpr REL::ID NiRTTI_NiPathController(static_cast<std::uint64_t>(524405));
	inline constexpr REL::ID NiRTTI_NiPathInterpolator(static_cast<std::uint64_t>(524344));
	inline constexpr REL::ID NiRTTI_NiPoint3InterpController(static_cast<std::uint64_t>(524460));
	inline constexpr REL::ID NiRTTI_NiPoint3Interpolator(static_cast<std::uint64_t>(524406));
	inline constexpr REL::ID NiRTTI_NiPointLight(static_cast<std::uint64_t>(523954));
	inline constexpr REL::ID NiRTTI_NiPosData(static_cast<std::uint64_t>(524378));
	inline constexpr REL::ID NiRTTI_NiProperty(static_cast<std::uint64_t>(523929));
	inline constexpr REL::ID NiRTTI_NiQuaternionInterpolator(static_cast<std::uint64_t>(524407));
	inline constexpr REL::ID NiRTTI_NiRollController(static_cast<std::uint64_t>(524408));
	inline constexpr REL::ID NiRTTI_NiRotData(static_cast<std::uint64_t>(524409));
	inline constexpr REL::ID NiRTTI_NiSequence(static_cast<std::uint64_t>(524410));
	inline constexpr REL::ID NiRTTI_NiSequenceStreamHelper(static_cast<std::uint64_t>(524413));
	inline constexpr REL::ID NiRTTI_NiShadeProperty(static_cast<std::uint64_t>(523987));
	inline constexpr REL::ID NiRTTI_NiSingleInterpController(static_cast<std::uint64_t>(524342));
	inline constexpr REL::ID NiRTTI_NiSkinData(static_cast<std::uint64_t>(523986));
	inline constexpr REL::ID NiRTTI_NiSkinInstance(static_cast<std::uint64_t>(523976));
	inline constexpr REL::ID NiRTTI_NiSkinPartition(static_cast<std::uint64_t>(523974));
	inline constexpr REL::ID NiRTTI_NiSourceTexture(static_cast<std::uint64_t>(523939));
	inline constexpr REL::ID NiRTTI_NiSpotLight(static_cast<std::uint64_t>(524007));
	inline constexpr REL::ID NiRTTI_NiStringExtraData(static_cast<std::uint64_t>(523942));
	inline constexpr REL::ID NiRTTI_NiStringPalette(static_cast<std::uint64_t>(524414));
	inline constexpr REL::ID NiRTTI_NiStringsExtraData(static_cast<std::uint64_t>(523925));
	inline constexpr REL::ID NiRTTI_NiSwitchNode(static_cast<std::uint64_t>(523924));
	inline constexpr REL::ID NiRTTI_NiSwitchStringExtraData(static_cast<std::uint64_t>(524008));
	inline constexpr REL::ID NiRTTI_NiTextKeyExtraData(static_cast<std::uint64_t>(524415));
	inline constexpr REL::ID NiRTTI_NiTexture(static_cast<std::uint64_t>(523967));
	inline constexpr REL::ID NiRTTI_NiTimeController(static_cast<std::uint64_t>(523943));
	inline constexpr REL::ID NiRTTI_NiTransformController(static_cast<std::uint64_t>(524351));
	inline constexpr REL::ID NiRTTI_NiTransformData(static_cast<std::uint64_t>(524377));
	inline constexpr REL::ID NiRTTI_NiTransformInterpolator(static_cast<std::uint64_t>(524343));
	inline constexpr REL::ID NiRTTI_NiTriBasedGeom(static_cast<std::uint64_t>(524027));
	inline constexpr REL::ID NiRTTI_NiTriBasedGeomData(static_cast<std::uint64_t>(524026));
	inline constexpr REL::ID NiRTTI_NiTriShape(static_cast<std::uint64_t>(524010));
	inline constexpr REL::ID NiRTTI_NiTriShapeData(static_cast<std::uint64_t>(524009));
	inline constexpr REL::ID NiRTTI_NiTriStrips(static_cast<std::uint64_t>(524012));
	inline constexpr REL::ID NiRTTI_NiTriStripsData(static_cast<std::uint64_t>(524011));
	inline constexpr REL::ID NiRTTI_NiUVData(static_cast<std::uint64_t>(524416));
	inline constexpr REL::ID NiRTTI_NiVectorExtraData(static_cast<std::uint64_t>(524013));
	inline constexpr REL::ID NiRTTI_NiVertWeightsExtraData(static_cast<std::uint64_t>(523975));
	inline constexpr REL::ID NiRTTI_NiVisController(static_cast<std::uint64_t>(524417));
	inline constexpr REL::ID NiRTTI_PArrayPoint(static_cast<std::uint64_t>(524602));
	inline constexpr REL::ID NiRTTI_REFRSyncController(static_cast<std::uint64_t>(514966));
	inline constexpr REL::ID NiRTTI_ReferenceEffect(static_cast<std::uint64_t>(516706));
	inline constexpr REL::ID NiRTTI_SceneGraph(static_cast<std::uint64_t>(517222));
	inline constexpr REL::ID NiRTTI_ShaderReferenceEffect(static_cast<std::uint64_t>(516712));
	inline constexpr REL::ID NiRTTI_ShadowSceneNode(static_cast<std::uint64_t>(527735));
	inline constexpr REL::ID NiRTTI_SummonPlacementEffect(static_cast<std::uint64_t>(516720));
	inline constexpr REL::ID NiRTTI_WeaponObject(static_cast<std::uint64_t>(525102));
	inline constexpr REL::ID NiRTTI_bhkAabbPhantom(static_cast<std::uint64_t>(525121));
	inline constexpr REL::ID NiRTTI_bhkAction(static_cast<std::uint64_t>(525160));
	inline constexpr REL::ID NiRTTI_bhkAngularDashpotAction(static_cast<std::uint64_t>(525243));
	inline constexpr REL::ID NiRTTI_bhkAttachmentCollisionObject(static_cast<std::uint64_t>(525101));
	inline constexpr REL::ID NiRTTI_bhkAutoWater(static_cast<std::uint64_t>(516226));
	inline constexpr REL::ID NiRTTI_bhkAvoidBox(static_cast<std::uint64_t>(525150));
	inline constexpr REL::ID NiRTTI_bhkBallAndSocketConstraint(static_cast<std::uint64_t>(525223));
	inline constexpr REL::ID NiRTTI_bhkBallSocketConstraintChain(static_cast<std::uint64_t>(525225));
	inline constexpr REL::ID NiRTTI_bhkBinaryAction(static_cast<std::uint64_t>(525460));
	inline constexpr REL::ID NiRTTI_bhkBlendCollisionObject(static_cast<std::uint64_t>(525147));
	inline constexpr REL::ID NiRTTI_bhkBlendController(static_cast<std::uint64_t>(525255));
	inline constexpr REL::ID NiRTTI_bhkBoxShape(static_cast<std::uint64_t>(525136));
	inline constexpr REL::ID NiRTTI_bhkBreakableConstraint(static_cast<std::uint64_t>(525241));
	inline constexpr REL::ID NiRTTI_bhkBvTreeShape(static_cast<std::uint64_t>(525140));
	inline constexpr REL::ID NiRTTI_bhkCachingShapePhantom(static_cast<std::uint64_t>(525177));
	inline constexpr REL::ID NiRTTI_bhkCapsuleShape(static_cast<std::uint64_t>(525134));
	inline constexpr REL::ID NiRTTI_bhkCartTether(static_cast<std::uint64_t>(515427));
	inline constexpr REL::ID NiRTTI_bhkCharControllerShape(static_cast<std::uint64_t>(525261));
	inline constexpr REL::ID NiRTTI_bhkCharacterProxy(static_cast<std::uint64_t>(525445));
	inline constexpr REL::ID NiRTTI_bhkCharacterRigidBody(static_cast<std::uint64_t>(525447));
	inline constexpr REL::ID NiRTTI_bhkCollisionBox(static_cast<std::uint64_t>(525263));
	inline constexpr REL::ID NiRTTI_bhkCollisionObject(static_cast<std::uint64_t>(525071));
	inline constexpr REL::ID NiRTTI_bhkCompressedMeshShape(static_cast<std::uint64_t>(525198));
	inline constexpr REL::ID NiRTTI_bhkCompressedMeshShapeData(static_cast<std::uint64_t>(525199));
	inline constexpr REL::ID NiRTTI_bhkConstraint(static_cast<std::uint64_t>(525156));
	inline constexpr REL::ID NiRTTI_bhkConstraintChain(static_cast<std::uint64_t>(525458));
	inline constexpr REL::ID NiRTTI_bhkConvexShape(static_cast<std::uint64_t>(525126));
	inline constexpr REL::ID NiRTTI_bhkConvexSweepShape(static_cast<std::uint64_t>(525201));
	inline constexpr REL::ID NiRTTI_bhkConvexTransformShape(static_cast<std::uint64_t>(525203));
	inline constexpr REL::ID NiRTTI_bhkConvexTranslateShape(static_cast<std::uint64_t>(525205));
	inline constexpr REL::ID NiRTTI_bhkConvexVerticesShape(static_cast<std::uint64_t>(525207));
	inline constexpr REL::ID NiRTTI_bhkCylinderShape(static_cast<std::uint64_t>(525209));
	inline constexpr REL::ID NiRTTI_bhkDashpotAction(static_cast<std::uint64_t>(525245));
	inline constexpr REL::ID NiRTTI_bhkEntity(static_cast<std::uint64_t>(525117));
	inline constexpr REL::ID NiRTTI_bhkExtraData(static_cast<std::uint64_t>(525256));
	inline constexpr REL::ID NiRTTI_bhkFixedConstraint(static_cast<std::uint64_t>(525231));
	inline constexpr REL::ID NiRTTI_bhkGenericConstraint(static_cast<std::uint64_t>(525260));
	inline constexpr REL::ID NiRTTI_bhkGroupConstraint(static_cast<std::uint64_t>(525227));
	inline constexpr REL::ID NiRTTI_bhkHeightFieldShape(static_cast<std::uint64_t>(525456));
	inline constexpr REL::ID NiRTTI_bhkHingeConstraint(static_cast<std::uint64_t>(525187));
	inline constexpr REL::ID NiRTTI_bhkHingeLimitsConstraint(static_cast<std::uint64_t>(525229));
	inline constexpr REL::ID NiRTTI_bhkLimitedHingeConstraint(static_cast<std::uint64_t>(525152));
	inline constexpr REL::ID NiRTTI_bhkLiquidAction(static_cast<std::uint64_t>(525247));
	inline constexpr REL::ID NiRTTI_bhkListShape(static_cast<std::uint64_t>(525221));
	inline constexpr REL::ID NiRTTI_bhkMalleableConstraint(static_cast<std::uint64_t>(525154));
	inline constexpr REL::ID NiRTTI_bhkMoppBvTreeShape(static_cast<std::uint64_t>(525217));
	inline constexpr REL::ID NiRTTI_bhkMotorAction(static_cast<std::uint64_t>(525250));
	inline constexpr REL::ID NiRTTI_bhkMouseSpringAction(static_cast<std::uint64_t>(525185));
	inline constexpr REL::ID NiRTTI_bhkMultiSphereShape(static_cast<std::uint64_t>(525211));
	inline constexpr REL::ID NiRTTI_bhkNiCollisionObject(static_cast<std::uint64_t>(525089));
	inline constexpr REL::ID NiRTTI_bhkNiTriStripsShape(static_cast<std::uint64_t>(525142));
	inline constexpr REL::ID NiRTTI_bhkOrientHingedBodyAction(static_cast<std::uint64_t>(525252));
	inline constexpr REL::ID NiRTTI_bhkPCollisionObject(static_cast<std::uint64_t>(525127));
	inline constexpr REL::ID NiRTTI_bhkPackedNiTriStripsShape(static_cast<std::uint64_t>(525145));
	inline constexpr REL::ID NiRTTI_bhkPhantom(static_cast<std::uint64_t>(525119));
	inline constexpr REL::ID NiRTTI_bhkPlaneShape(static_cast<std::uint64_t>(525213));
	inline constexpr REL::ID NiRTTI_bhkPointToPathConstraint(static_cast<std::uint64_t>(525466));
	inline constexpr REL::ID NiRTTI_bhkPoseArray(static_cast<std::uint64_t>(525257));
	inline constexpr REL::ID NiRTTI_bhkPositionConstraintMotor(static_cast<std::uint64_t>(525267));
	inline constexpr REL::ID NiRTTI_bhkPrismaticConstraint(static_cast<std::uint64_t>(525158));
	inline constexpr REL::ID NiRTTI_bhkRagdollConstraint(static_cast<std::uint64_t>(525233));
	inline constexpr REL::ID NiRTTI_bhkRagdollLimitsConstraint(static_cast<std::uint64_t>(525235));
	inline constexpr REL::ID NiRTTI_bhkRagdollTemplate(static_cast<std::uint64_t>(525182));
	inline constexpr REL::ID NiRTTI_bhkRagdollTemplateData(static_cast<std::uint64_t>(525181));
	inline constexpr REL::ID NiRTTI_bhkRefObject(static_cast<std::uint64_t>(525108));
	inline constexpr REL::ID NiRTTI_bhkRigidBody(static_cast<std::uint64_t>(525068));
	inline constexpr REL::ID NiRTTI_bhkRigidBodyT(static_cast<std::uint64_t>(525106));
	inline constexpr REL::ID NiRTTI_bhkSPCollisionObject(static_cast<std::uint64_t>(525183));
	inline constexpr REL::ID NiRTTI_bhkSerializable(static_cast<std::uint64_t>(525109));
	inline constexpr REL::ID NiRTTI_bhkShape(static_cast<std::uint64_t>(525115));
	inline constexpr REL::ID NiRTTI_bhkShapeCollection(static_cast<std::uint64_t>(525265));
	inline constexpr REL::ID NiRTTI_bhkShapePhantom(static_cast<std::uint64_t>(525130));
	inline constexpr REL::ID NiRTTI_bhkSimpleShapePhantom(static_cast<std::uint64_t>(525132));
	inline constexpr REL::ID NiRTTI_bhkSphereRepShape(static_cast<std::uint64_t>(525123));
	inline constexpr REL::ID NiRTTI_bhkSphereShape(static_cast<std::uint64_t>(525138));
	inline constexpr REL::ID NiRTTI_bhkSpringAction(static_cast<std::uint64_t>(525254));
	inline constexpr REL::ID NiRTTI_bhkSpringDamperConstraintMotor(static_cast<std::uint64_t>(525269));
	inline constexpr REL::ID NiRTTI_bhkStiffSpringConstraint(static_cast<std::uint64_t>(525237));
	inline constexpr REL::ID NiRTTI_bhkTiltPreventAction(static_cast<std::uint64_t>(515428));
	inline constexpr REL::ID NiRTTI_bhkTransformShape(static_cast<std::uint64_t>(525219));
	inline constexpr REL::ID NiRTTI_bhkTriSampledHeightFieldBvTreeShape(static_cast<std::uint64_t>(525164));
	inline constexpr REL::ID NiRTTI_bhkTriangleShape(static_cast<std::uint64_t>(525215));
	inline constexpr REL::ID NiRTTI_bhkUnaryAction(static_cast<std::uint64_t>(525162));
	inline constexpr REL::ID NiRTTI_bhkVelocityConstraintMotor(static_cast<std::uint64_t>(525268));
	inline constexpr REL::ID NiRTTI_bhkWheelAction(static_cast<std::uint64_t>(515429));
	inline constexpr REL::ID NiRTTI_bhkWheelConstraint(static_cast<std::uint64_t>(525239));
	inline constexpr REL::ID NiRTTI_bhkWorld(static_cast<std::uint64_t>(525051));
	inline constexpr REL::ID NiRTTI_bhkWorldM(static_cast<std::uint64_t>(525107));
	inline constexpr REL::ID NiRTTI_bhkWorldObject(static_cast<std::uint64_t>(525039));
	inline constexpr REL::ID NiRTTI_hkPackedNiTriStripsData(static_cast<std::uint64_t>(525128));
#endif
}
